# Array Shape, Dimensions, and Index Positions (NumPy)

This notebook explains:
- `shape` and what each number means
- `ndim` (number of dimensions)
- correct indexing for 1D and 2D arrays
- how to avoid out-of-range index errors

In [1]:
import numpy as np
print("NumPy imported successfully.")

NumPy imported successfully.


## 1) 1D array: shape and indexing
A 1D array has one axis, so `shape` looks like `(N,)`.
Indexing is zero-based: valid indices are `0` to `N-1`.

In [2]:
arr_1d = np.array([10, 20, 30, 40])

print("arr_1d:", arr_1d)
print("shape:", arr_1d.shape)
print("ndim:", arr_1d.ndim)

print("arr_1d[0] (first element):", arr_1d[0])
print("arr_1d[2] (third element):", arr_1d[2])

arr_1d: [10 20 30 40]
shape: (4,)
ndim: 1
arr_1d[0] (first element): 10
arr_1d[2] (third element): 30


## 2) 2D array: interpret shape as rows and columns
A 2D array looks like a grid/table.
`shape` is `(rows, cols)`.
Access elements with: `arr_2d[row_index, col_index]` (both zero-based).

In [3]:
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("arr_2d:\n", arr_2d)
print("shape:", arr_2d.shape)
print("ndim:", arr_2d.ndim)

print("arr_2d[0, 0] (row 0, col 0):", arr_2d[0, 0])  # top-left
print("arr_2d[0, 2] (row 0, col 2):", arr_2d[0, 2])  # top-right
print("arr_2d[1, 1] (row 1, col 1):", arr_2d[1, 1])  # second row, middle

arr_2d:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
ndim: 2
arr_2d[0, 0] (row 0, col 0): 1
arr_2d[0, 2] (row 0, col 2): 3
arr_2d[1, 1] (row 1, col 1): 5


## 3) Avoid out-of-range indexing (show the error safely)
If you use an index that is outside the valid range, NumPy raises an `IndexError`.
We’ll demonstrate and catch it so the notebook continues.

In [4]:
print("Attempting out-of-range indexing on arr_1d...")

try:
    print(arr_1d[10])  # invalid: arr_1d has only indices 0..3
except IndexError as e:
    print("Caught IndexError:", e)

Attempting out-of-range indexing on arr_1d...
Caught IndexError: index 10 is out of bounds for axis 0 with size 4


## 4) Reshape to see how shape changes (optional but recommended)
Reshaping changes the layout, so `shape` and how you index will also change accordingly.

In [5]:
arr_2x2 = np.array([10, 20, 30, 40]).reshape(2, 2)

print("arr_2x2:\n", arr_2x2)
print("shape:", arr_2x2.shape)
print("ndim:", arr_2x2.ndim)

print("arr_2x2[0, 1] (row 0, col 1):", arr_2x2[0, 1])

arr_2x2:
 [[10 20]
 [30 40]]
shape: (2, 2)
ndim: 2
arr_2x2[0, 1] (row 0, col 1): 20


## Summary
- `shape` describes the layout (for 2D: `(rows, cols)`).
- `ndim` tells how many dimensions/axes the array has.
- 1D indexing: `arr[i]`
- 2D indexing: `arr[row, col]`
- Indices are zero-based, and out-of-range indices raise `IndexError`.